INSERT INTO additional_info_clients VALUES (null, "ul. Alberta 3/43, 01-577 Warszawa", "77249000056420077578477743", "kulczyk.j@gmail.com", 550, "9318235090", "879876543")
INSERT INTO additional_info_clients VALUES (null, "ul. Krecia 2, 01-343 Warszawa", "86106000058780488477816280", "tarcz.and@onet.pl", 480, "8943064667", "564432123")
INSERT INTO additional_info_clients VALUES (null, "ul. Zamszy 7, 01-434 Warszawa", "59150017356396376097274923", "info.polexport@polex.pl", 700, "1219027734", "512098876")
INSERT INTO additional_info_clients VALUES (null, "ul. Sienna 39, 01-101 Warszawa", "56124067132770425575384752", "info@PKlegal.pl", 500, "7991032682", "542765432")

INSERT INTO clients_natural_person VALUES (1000, 1, "Janusz", "Kulczyk")
INSERT INTO clients_natural_person VALUES (1001, 11, "Andrzej", "Tarczynski")
INSERT INTO clients_legal_person VALUES (1002, 21, "PolExport sp. z o.o.")
INSERT INTO clients_legal_person VALUES (1003, 31 , "Kancelaria")

INSERT INTO additional_info_employees VALUES (null, 10, 500, 300, "546434654", 60000)
INSERT INTO additional_info_employees VALUES (null, 8, 400, 100, "634567987", 20000)
INSERT INTO additional_info_employees VALUES (null, 5, 300, 60, "765456987", 12000)
INSERT INTO additional_info_employees VALUES (null, 0, 200, 40, "546768987", 9000)
INSERT INTO additional_info_employees VALUES (null, 15, 600, 400, "654765876", 80000)

INSERT INTO employees VALUES (null, "adam.kowalski@PKlegal.pl", "Adam", 1, "Kowalski", "$2a$10$LusF4zmyfIfHTvA8KKSLEO.lrY8Y6LX4UHo99uqV0.sS2D5EJZAPi", 1)
INSERT INTO employees VALUES (null, "k.janicki@PKlegal.pl", "Krzysztof", 0, "Janicki", "$2a$10$fgAg6NLP7JIHjiyOl5.Z0uNArcKjrthwOFEYsqMkWU3K.DScXtZi6", 11)
INSERT INTO employees VALUES (null, "patryk.zubrzycki@PKlegal.pl", "Patryk", 0, "Zubrzycki", "$2a$10$3Zt7i.Zwjr0bahsObyu0vuVJENxQWEPYvqciZExZM4ki1NpCodyMe", 21)
INSERT INTO employees VALUES (null, "pawel.janiak@PKlegal.pl", "Pawel", 0, "Janiak", "$2a$10$4JUnbHe/sW1o8NOUYt9dRuzL8wQitlHZOjoIQtfwjZRK9nIHVxpr6", 31)
INSERT INTO employees VALUES (null, "zenon.krzywiski@PKlegal.pl", "Zenon", 0, "Krzywiski", "$2a$10$6NTqm.zz3H6wTlPbgR7lU.xGq0W.C9Ir5WgDZpADnSlANGi8yOCwW", 41)

INSERT INTO authority VALUES (null, 'ROLE_ADMIN');
INSERT INTO authority VALUES (null, 'ROLE_USER');

INSERT INTO employee_authority VALUES (1, 1);
INSERT INTO employee_authority VALUES (11, 11);
INSERT INTO employee_authority VALUES (21, 11);
INSERT INTO employee_authority VALUES (31, 11);
INSERT INTO employee_authority VALUES (41, 11);

INSERT INTO projects VALUES (null, 100000, "divorce of the client with his spouse; client demands alimony from his wife", true, "divorce", "2019/06/fam", 1000)
INSERT INTO projects VALUES (null, 50000, "client's wish is to sue his former employer for damages incurred during his employment time", true, "damages", "2017/01/civ", 1000)
INSERT INTO projects VALUES (null, 200000, "client is investigated by the tax office due to tax arrears in fiscal year 2018", true, "tax dispute", "2019/07/tax", 1001)
INSERT INTO projects VALUES (null, 250000, "merger of the parent company with its subsidiary in Cyprus", true, "merger", "2018/08/com", 1002)
INSERT INTO projects VALUES (null, 0, "non billable actvities - private development etc.", false, "private development", "PD/nonBillable", 1003)

INSERT INTO project_employee VALUES (1, 1)
INSERT INTO project_employee VALUES (1, 11)
INSERT INTO project_employee VALUES (11, 21)
INSERT INTO project_employee VALUES (11, 31)
INSERT INTO project_employee VALUES (21, 41)
INSERT INTO project_employee VALUES (21, 1)
INSERT INTO project_employee VALUES (21, 11)
INSERT INTO project_employee VALUES (31, 21)
INSERT INTO project_employee VALUES (31, 31)
INSERT INTO project_employee VALUES (31, 41)
INSERT INTO project_employee VALUES (41, 1)
INSERT INTO project_employee VALUES (41, 11)
INSERT INTO project_employee VALUES (41, 21)
INSERT INTO project_employee VALUES (41, 31)
INSERT INTO project_employee VALUES (41, 41)

INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")
INSERT INTO commentary VALUES (null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt","","", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt")

INSERT INTO timesheet_week VALUES (null, "2019-07-01", 4, 5, 0, 0, 3, 7, 2, 1)
INSERT INTO timesheet_week VALUES (null, "2019-07-01", 4, 3, 0, 0, 5, 1, 6, 11)
INSERT INTO timesheet_week VALUES (null, "2019-07-01", 1, 3, 0, 0, 3, 7, 4, 21)
INSERT INTO timesheet_week VALUES (null, "2019-07-01", 7, 5, 0, 0, 5, 1, 4, 31)
INSERT INTO timesheet_week VALUES (null, "2019-07-01", 1, 3, 0, 0, 3, 6, 8, 41)
INSERT INTO timesheet_week VALUES (null, "2019-07-01", 7, 5, 0, 0, 5, 2, 1, 51)
INSERT INTO timesheet_week VALUES (null, "2019-07-01", 3, 2, 0, 0, 3, 7, 2, 61)
INSERT INTO timesheet_week VALUES (null, "2019-07-01", 5, 6, 0, 0, 5, 1, 6, 71)
INSERT INTO timesheet_week VALUES (null, "2019-07-01", 4, 3, 0, 0, 2, 4, 3, 81)
INSERT INTO timesheet_week VALUES (null, "2019-07-01", 4, 5, 0, 0, 6, 4, 5, 91)
INSERT INTO timesheet_week VALUES (null, "2019-07-08", 4, 5, 0, 0, 3, 7, 2, 101)
INSERT INTO timesheet_week VALUES (null, "2019-07-08", 4, 3, 0, 0, 5, 1, 6, 111)
INSERT INTO timesheet_week VALUES (null, "2019-07-08", 1, 3, 0, 0, 3, 7, 4, 121)
INSERT INTO timesheet_week VALUES (null, "2019-07-08", 7, 5, 0, 0, 5, 1, 4, 131)
INSERT INTO timesheet_week VALUES (null, "2019-07-08", 1, 3, 0, 0, 3, 6, 8, 141)
INSERT INTO timesheet_week VALUES (null, "2019-07-08", 7, 5, 0, 0, 5, 2, 1, 151)
INSERT INTO timesheet_week VALUES (null, "2019-07-08", 3, 2, 0, 0, 3, 7, 2, 161)
INSERT INTO timesheet_week VALUES (null, "2019-07-08", 5, 6, 0, 0, 5, 1, 6, 171)
INSERT INTO timesheet_week VALUES (null, "2019-07-08", 4, 3, 0, 0, 2, 4, 3, 181)
INSERT INTO timesheet_week VALUES (null, "2019-07-08", 4, 5, 0, 0, 6, 4, 5, 191)
INSERT INTO timesheet_week VALUES (null, "2019-07-15", 4, 5, 0, 0, 3, 7, 2, 201)
INSERT INTO timesheet_week VALUES (null, "2019-07-15", 4, 3, 0, 0, 5, 1, 6, 211)
INSERT INTO timesheet_week VALUES (null, "2019-07-15", 1, 3, 0, 0, 3, 7, 4, 221)
INSERT INTO timesheet_week VALUES (null, "2019-07-15", 7, 5, 0, 0, 5, 1, 4, 231)
INSERT INTO timesheet_week VALUES (null, "2019-07-15", 1, 3, 0, 0, 3, 6, 8, 241)
INSERT INTO timesheet_week VALUES (null, "2019-07-15", 7, 5, 0, 0, 5, 2, 1, 251)
INSERT INTO timesheet_week VALUES (null, "2019-07-15", 3, 2, 0, 0, 3, 7, 2, 261)
INSERT INTO timesheet_week VALUES (null, "2019-07-15", 5, 6, 0, 0, 5, 1, 6, 271)
INSERT INTO timesheet_week VALUES (null, "2019-07-15", 4, 3, 0, 0, 2, 4, 3, 281)
INSERT INTO timesheet_week VALUES (null, "2019-07-15", 4, 5, 0, 0, 6, 4, 5, 291)
INSERT INTO timesheet_week VALUES (null, "2019-07-22", 4, 5, 0, 0, 6, 4, 5, 301)
INSERT INTO timesheet_week VALUES (null, "2019-07-22", 4, 3, 0, 0, 2, 4, 3, 311)
INSERT INTO timesheet_week VALUES (null, "2019-07-22", 4, 5, 0, 0, 6, 4, 5, 321)
INSERT INTO timesheet_week VALUES (null, "2019-07-22", 4, 3, 0, 0, 2, 4, 3, 331)
INSERT INTO timesheet_week VALUES (null, "2019-07-22", 4, 5, 0, 0, 6, 4, 5, 341)
INSERT INTO timesheet_week VALUES (null, "2019-07-22", 4, 3, 0, 0, 2, 4, 3, 351)
INSERT INTO timesheet_week VALUES (null, "2019-07-22", 4, 5, 0, 0, 6, 4, 5, 361)
INSERT INTO timesheet_week VALUES (null, "2019-07-22", 4, 3, 0, 0, 2, 4, 3, 371)
INSERT INTO timesheet_week VALUES (null, "2019-07-22", 4, 5, 0, 0, 6, 4, 5, 381)
INSERT INTO timesheet_week VALUES (null, "2019-07-22", 4, 3, 0, 0, 2, 4, 3, 391)
INSERT INTO timesheet_week VALUES (null, "2019-07-29", 4, 5, 0, 0, 6, 4, 5, 401)
INSERT INTO timesheet_week VALUES (null, "2019-07-29", 4, 3, 0, 0, 2, 4, 3, 411)
INSERT INTO timesheet_week VALUES (null, "2019-07-29", 4, 5, 0, 0, 6, 4, 5, 421)
INSERT INTO timesheet_week VALUES (null, "2019-07-29", 4, 3, 0, 0, 2, 4, 3, 431)
INSERT INTO timesheet_week VALUES (null, "2019-07-29", 4, 5, 0, 0, 6, 4, 5, 441)
INSERT INTO timesheet_week VALUES (null, "2019-07-29", 4, 3, 0, 0, 2, 4, 3, 451)
INSERT INTO timesheet_week VALUES (null, "2019-07-29", 4, 5, 0, 0, 6, 4, 5, 461)
INSERT INTO timesheet_week VALUES (null, "2019-07-29", 4, 3, 0, 0, 2, 4, 3, 471)
INSERT INTO timesheet_week VALUES (null, "2019-07-29", 4, 5, 0, 0, 6, 4, 5, 481)
INSERT INTO timesheet_week VALUES (null, "2019-07-29", 4, 3, 0, 0, 2, 4, 3, 491)
INSERT INTO timesheet_week VALUES (null, "2019-08-05", 4, 5, 0, 0, 3, 7, 2, 501)
INSERT INTO timesheet_week VALUES (null, "2019-08-05", 4, 3, 0, 0, 5, 1, 6, 511)
INSERT INTO timesheet_week VALUES (null, "2019-08-05", 1, 3, 0, 0, 3, 7, 4, 521)
INSERT INTO timesheet_week VALUES (null, "2019-08-05", 7, 5, 0, 0, 5, 1, 4, 531)
INSERT INTO timesheet_week VALUES (null, "2019-08-05", 1, 3, 0, 0, 3, 6, 8, 541)
INSERT INTO timesheet_week VALUES (null, "2019-08-05", 7, 5, 0, 0, 5, 2, 1, 551)
INSERT INTO timesheet_week VALUES (null, "2019-08-05", 3, 2, 0, 0, 3, 7, 2, 561)
INSERT INTO timesheet_week VALUES (null, "2019-08-05", 5, 6, 0, 0, 5, 1, 6, 571)
INSERT INTO timesheet_week VALUES (null, "2019-08-05", 4, 3, 0, 0, 2, 4, 3, 581)
INSERT INTO timesheet_week VALUES (null, "2019-08-05", 4, 5, 0, 0, 6, 4, 5, 591)
INSERT INTO timesheet_week VALUES (null, "2019-08-12", 4, 5, 0, 0, 6, 4, 5, 601)
INSERT INTO timesheet_week VALUES (null, "2019-08-12", 4, 3, 0, 0, 2, 4, 3, 611)
INSERT INTO timesheet_week VALUES (null, "2019-08-12", 4, 5, 0, 0, 6, 4, 5, 621)
INSERT INTO timesheet_week VALUES (null, "2019-08-12", 4, 3, 0, 0, 2, 4, 3, 631)
INSERT INTO timesheet_week VALUES (null, "2019-08-12", 4, 5, 0, 0, 6, 4, 5, 641)
INSERT INTO timesheet_week VALUES (null, "2019-08-12", 4, 3, 0, 0, 2, 4, 3, 651)
INSERT INTO timesheet_week VALUES (null, "2019-08-12", 4, 5, 0, 0, 6, 4, 5, 661)
INSERT INTO timesheet_week VALUES (null, "2019-08-12", 4, 3, 0, 0, 2, 4, 3, 671)
INSERT INTO timesheet_week VALUES (null, "2019-08-12", 4, 5, 0, 0, 6, 4, 5, 681)
INSERT INTO timesheet_week VALUES (null, "2019-08-12", 4, 3, 0, 0, 2, 4, 3, 691)
INSERT INTO timesheet_week VALUES (null, "2019-08-19", 4, 5, 0, 0, 6, 4, 5, 701)
INSERT INTO timesheet_week VALUES (null, "2019-08-19", 4, 3, 0, 0, 2, 4, 3, 711)
INSERT INTO timesheet_week VALUES (null, "2019-08-19", 4, 5, 0, 0, 6, 4, 5, 721)
INSERT INTO timesheet_week VALUES (null, "2019-08-19", 4, 3, 0, 0, 2, 4, 3, 731)
INSERT INTO timesheet_week VALUES (null, "2019-08-19", 4, 5, 0, 0, 6, 4, 5, 741)
INSERT INTO timesheet_week VALUES (null, "2019-08-19", 4, 3, 0, 0, 2, 4, 3, 751)
INSERT INTO timesheet_week VALUES (null, "2019-08-19", 4, 5, 0, 0, 6, 4, 5, 761)
INSERT INTO timesheet_week VALUES (null, "2019-08-19", 4, 3, 0, 0, 2, 4, 3, 771)
INSERT INTO timesheet_week VALUES (null, "2019-08-19", 4, 5, 0, 0, 6, 4, 5, 781)
INSERT INTO timesheet_week VALUES (null, "2019-08-19", 4, 3, 0, 0, 2, 4, 3, 791)
INSERT INTO timesheet_week VALUES (null, "2019-08-26", 4, 5, 0, 0, 3, 7, 2, 801)
INSERT INTO timesheet_week VALUES (null, "2019-08-26", 4, 3, 0, 0, 5, 1, 6, 811)
INSERT INTO timesheet_week VALUES (null, "2019-08-26", 1, 3, 0, 0, 3, 7, 4, 821)
INSERT INTO timesheet_week VALUES (null, "2019-08-26", 7, 5, 0, 0, 5, 1, 4, 831)
INSERT INTO timesheet_week VALUES (null, "2019-08-26", 1, 3, 0, 0, 3, 6, 8, 841)
INSERT INTO timesheet_week VALUES (null, "2019-08-26", 7, 5, 0, 0, 5, 2, 1, 851)
INSERT INTO timesheet_week VALUES (null, "2019-08-26", 3, 2, 0, 0, 3, 7, 2, 861)
INSERT INTO timesheet_week VALUES (null, "2019-08-26", 5, 6, 0, 0, 5, 1, 6, 871)
INSERT INTO timesheet_week VALUES (null, "2019-08-26", 4, 3, 0, 0, 2, 4, 3, 881)
INSERT INTO timesheet_week VALUES (null, "2019-08-26", 4, 5, 0, 0, 6, 4, 5, 891)
INSERT INTO timesheet_week VALUES (null, "2019-09-02", 4, 5, 0, 0, 3, 7, 2, 901)
INSERT INTO timesheet_week VALUES (null, "2019-09-02", 4, 3, 0, 0, 5, 1, 6, 911)
INSERT INTO timesheet_week VALUES (null, "2019-09-02", 1, 3, 0, 0, 3, 7, 4, 921)
INSERT INTO timesheet_week VALUES (null, "2019-09-02", 7, 5, 0, 0, 5, 1, 4, 931)
INSERT INTO timesheet_week VALUES (null, "2019-09-02", 1, 3, 0, 0, 3, 6, 8, 941)
INSERT INTO timesheet_week VALUES (null, "2019-09-02", 7, 5, 0, 0, 5, 2, 1, 951)
INSERT INTO timesheet_week VALUES (null, "2019-09-26", 3, 2, 0, 0, 3, 7, 2, 961)
INSERT INTO timesheet_week VALUES (null, "2019-09-02", 5, 6, 0, 0, 5, 1, 6, 971)
INSERT INTO timesheet_week VALUES (null, "2019-09-02", 4, 3, 0, 0, 2, 4, 3, 981)
INSERT INTO timesheet_week VALUES (null, "2019-09-02", 4, 5, 0, 0, 6, 4, 5, 991)
INSERT INTO timesheet_week VALUES (null, "2019-07-01", 1, 2, 3, 4, 5, 6, 7, 1001)
INSERT INTO timesheet_week VALUES (null, "2019-07-08", 8, 9, 10, 11, 12, 13, 14, 1011)
INSERT INTO timesheet_week VALUES (null, "2019-07-15", 15, 16, 17, 18, 19, 20, 21, 1021)
INSERT INTO timesheet_week VALUES (null, "2019-07-22", 22, 23, 24, 1, 2, 4, 3, 1031)
INSERT INTO timesheet_week VALUES (null, "2019-07-29", 5, 6, 7, 8, 9, 10, 11, 1041)
INSERT INTO timesheet_week VALUES (null, "2019-08-05", 12, 13, 14, 15, 16, 17, 18, 1051)
INSERT INTO timesheet_week VALUES (null, "2019-08-12", 19, 20, 21, 22, 23, 24, 1, 1061)
INSERT INTO timesheet_week VALUES (null, "2019-08-19", 2, 3, 4, 5, 6, 7, 8, 1071)
INSERT INTO timesheet_week VALUES (null, "2019-08-26", 9, 10, 11, 12, 13, 14, 15, 1081)
INSERT INTO timesheet_week VALUES (null, "2019-09-02", 16, 17, 18, 19, 20, 21, 22, 1091)

INSERT INTO timesheet_reference_unit VALUES (null, 1, 1, 1)
INSERT INTO timesheet_reference_unit VALUES (null, 1, 21, 11)
INSERT INTO timesheet_reference_unit VALUES (null, 11, 1, 21)
INSERT INTO timesheet_reference_unit VALUES (null, 11, 21, 31)
INSERT INTO timesheet_reference_unit VALUES (null, 21, 11, 41)
INSERT INTO timesheet_reference_unit VALUES (null, 21, 31, 51)
INSERT INTO timesheet_reference_unit VALUES (null, 31, 11, 61)
INSERT INTO timesheet_reference_unit VALUES (null, 31, 31, 71)
INSERT INTO timesheet_reference_unit VALUES (null, 41, 21, 81)
INSERT INTO timesheet_reference_unit VALUES (null, 41, 31, 91)
INSERT INTO timesheet_reference_unit VALUES (null, 41, 21, 101)
INSERT INTO timesheet_reference_unit VALUES (null, 41, 31, 111)
INSERT INTO timesheet_reference_unit VALUES (null, 31, 11, 121)
INSERT INTO timesheet_reference_unit VALUES (null, 31, 31, 131)
INSERT INTO timesheet_reference_unit VALUES (null, 21, 11, 141)
INSERT INTO timesheet_reference_unit VALUES (null, 21, 31, 151)
INSERT INTO timesheet_reference_unit VALUES (null, 11, 1, 161)
INSERT INTO timesheet_reference_unit VALUES (null, 11, 21, 171)
INSERT INTO timesheet_reference_unit VALUES (null, 1, 1, 181)
INSERT INTO timesheet_reference_unit VALUES (null, 1, 21, 191)
INSERT INTO timesheet_reference_unit VALUES (null, 1, 1, 201)
INSERT INTO timesheet_reference_unit VALUES (null, 1, 21, 211)
INSERT INTO timesheet_reference_unit VALUES (null, 11, 1, 221)
INSERT INTO timesheet_reference_unit VALUES (null, 11, 21, 231)
INSERT INTO timesheet_reference_unit VALUES (null, 21, 11, 241)
INSERT INTO timesheet_reference_unit VALUES (null, 21, 31, 251)
INSERT INTO timesheet_reference_unit VALUES (null, 31, 11, 261)
INSERT INTO timesheet_reference_unit VALUES (null, 31, 31, 271)
INSERT INTO timesheet_reference_unit VALUES (null, 41, 21, 281)
INSERT INTO timesheet_reference_unit VALUES (null, 41, 31, 291)
INSERT INTO timesheet_reference_unit VALUES (null, 1, 1, 301)
INSERT INTO timesheet_reference_unit VALUES (null, 1, 21, 311)
INSERT INTO timesheet_reference_unit VALUES (null, 11, 1, 321)
INSERT INTO timesheet_reference_unit VALUES (null, 11, 21, 331)
INSERT INTO timesheet_reference_unit VALUES (null, 21, 11, 341)
INSERT INTO timesheet_reference_unit VALUES (null, 21, 31, 351)
INSERT INTO timesheet_reference_unit VALUES (null, 31, 11, 361)
INSERT INTO timesheet_reference_unit VALUES (null, 31, 31, 371)
INSERT INTO timesheet_reference_unit VALUES (null, 41, 21, 381)
INSERT INTO timesheet_reference_unit VALUES (null, 41, 31, 391)
INSERT INTO timesheet_reference_unit VALUES (null, 41, 21, 401)
INSERT INTO timesheet_reference_unit VALUES (null, 41, 31, 411)
INSERT INTO timesheet_reference_unit VALUES (null, 31, 21, 421)
INSERT INTO timesheet_reference_unit VALUES (null, 31, 31, 431)
INSERT INTO timesheet_reference_unit VALUES (null, 21, 11, 441)
INSERT INTO timesheet_reference_unit VALUES (null, 21, 31, 451)
INSERT INTO timesheet_reference_unit VALUES (null, 11, 1, 461)
INSERT INTO timesheet_reference_unit VALUES (null, 11, 21, 471)
INSERT INTO timesheet_reference_unit VALUES (null, 1, 1, 481)
INSERT INTO timesheet_reference_unit VALUES (null, 1, 21, 491)
INSERT INTO timesheet_reference_unit VALUES (null, 1, 1, 501)
INSERT INTO timesheet_reference_unit VALUES (null, 1, 21, 511)
INSERT INTO timesheet_reference_unit VALUES (null, 11, 1, 521)
INSERT INTO timesheet_reference_unit VALUES (null, 11, 21, 531)
INSERT INTO timesheet_reference_unit VALUES (null, 21, 11, 541)
INSERT INTO timesheet_reference_unit VALUES (null, 21, 31, 551)
INSERT INTO timesheet_reference_unit VALUES (null, 31, 11, 561)
INSERT INTO timesheet_reference_unit VALUES (null, 31, 31, 571)
INSERT INTO timesheet_reference_unit VALUES (null, 41, 21, 581)
INSERT INTO timesheet_reference_unit VALUES (null, 51, 31, 591)
INSERT INTO timesheet_reference_unit VALUES (null, 1, 1, 601)
INSERT INTO timesheet_reference_unit VALUES (null, 1, 21, 611)
INSERT INTO timesheet_reference_unit VALUES (null, 11, 1, 621)
INSERT INTO timesheet_reference_unit VALUES (null, 11, 21, 631)
INSERT INTO timesheet_reference_unit VALUES (null, 21, 11, 641)
INSERT INTO timesheet_reference_unit VALUES (null, 21, 31, 651)
INSERT INTO timesheet_reference_unit VALUES (null, 31, 11, 661)
INSERT INTO timesheet_reference_unit VALUES (null, 31, 31, 671)
INSERT INTO timesheet_reference_unit VALUES (null, 41, 21, 681)
INSERT INTO timesheet_reference_unit VALUES (null, 41, 31, 691)
INSERT INTO timesheet_reference_unit VALUES (null, 41, 21, 701)
INSERT INTO timesheet_reference_unit VALUES (null, 41, 31, 711)
INSERT INTO timesheet_reference_unit VALUES (null, 31, 11, 721)
INSERT INTO timesheet_reference_unit VALUES (null, 31, 31, 731)
INSERT INTO timesheet_reference_unit VALUES (null, 21, 11, 741)
INSERT INTO timesheet_reference_unit VALUES (null, 21, 31, 751)
INSERT INTO timesheet_reference_unit VALUES (null, 11, 1, 761)
INSERT INTO timesheet_reference_unit VALUES (null, 11, 21, 771)
INSERT INTO timesheet_reference_unit VALUES (null, 1, 1, 781)
INSERT INTO timesheet_reference_unit VALUES (null, 1, 21, 791)
INSERT INTO timesheet_reference_unit VALUES (null, 41, 21, 801)
INSERT INTO timesheet_reference_unit VALUES (null, 41, 31, 811)
INSERT INTO timesheet_reference_unit VALUES (null, 31, 11, 821)
INSERT INTO timesheet_reference_unit VALUES (null, 31, 31, 831)
INSERT INTO timesheet_reference_unit VALUES (null, 21, 11, 841)
INSERT INTO timesheet_reference_unit VALUES (null, 21, 31, 851)
INSERT INTO timesheet_reference_unit VALUES (null, 11, 1, 861)
INSERT INTO timesheet_reference_unit VALUES (null, 11, 21, 871)
INSERT INTO timesheet_reference_unit VALUES (null, 1, 1, 881)
INSERT INTO timesheet_reference_unit VALUES (null, 1, 21, 891)
INSERT INTO timesheet_reference_unit VALUES (null, 1, 1, 901)
INSERT INTO timesheet_reference_unit VALUES (null, 1, 21, 911)
INSERT INTO timesheet_reference_unit VALUES (null, 11, 1, 921)
INSERT INTO timesheet_reference_unit VALUES (null, 11, 21, 931)
INSERT INTO timesheet_reference_unit VALUES (null, 21, 11, 941)
INSERT INTO timesheet_reference_unit VALUES (null, 21, 31, 951)
INSERT INTO timesheet_reference_unit VALUES (null, 31, 11, 961)
INSERT INTO timesheet_reference_unit VALUES (null, 31, 31, 971)
INSERT INTO timesheet_reference_unit VALUES (null, 41, 21, 981)
INSERT INTO timesheet_reference_unit VALUES (null, 41, 31, 991)
INSERT INTO timesheet_reference_unit VALUES (null, 1, 41, 1001)
INSERT INTO timesheet_reference_unit VALUES (null, 11, 41, 1011)
INSERT INTO timesheet_reference_unit VALUES (null, 21, 41, 1021)
INSERT INTO timesheet_reference_unit VALUES (null, 31, 41, 1031)
INSERT INTO timesheet_reference_unit VALUES (null, 41, 41, 1041)
INSERT INTO timesheet_reference_unit VALUES (null, 1, 41, 1051)
INSERT INTO timesheet_reference_unit VALUES (null, 11, 41, 1061)
INSERT INTO timesheet_reference_unit VALUES (null, 21, 41, 1071)
INSERT INTO timesheet_reference_unit VALUES (null, 31, 41, 1081)
INSERT INTO timesheet_reference_unit VALUES (null, 41, 41, 1091)



